<p align="center">
  <img src="./assets/banner.png" alt="Room generated by Midjourney" width="100%">
</p>

👋 &nbsp;**Hello**&nbsp;&nbsp;&nbsp; ℹ️ &nbsp;[Website](https://revcd.com)&nbsp;&nbsp;&nbsp; 🐦 &nbsp;[Twitter](https://twitter.com/revcd)&nbsp;&nbsp;&nbsp; 💼 &nbsp;[LinkedIn](https://www.linkedin.com/in/cdrev/)&nbsp;&nbsp; 🥋 [Katas](https://www.codewars.com/users/revett)

Recent projects:

- [`atlas`](https://github.com/revett/atlas) - CLI focused personal knowledge management tool
- [`rss-explore`](https://github.com/revett/rss-explore) - Tools to help you easily find and manage RSS feeds

Ongoing utility projects:

- [`common`](https://github.com/revett/common) - Shared common code for my Go projects
- [`dotfiles`](https://github.com/revett/dotfiles) - macOS .files and configuration
- [`revcd.com`](https://github.com/revett/revcd.com) - Personal website

Archived projects:

- [`everyman-rss`](https://github.com/revett/everyman-rss) - (April 2023) RSS feeds for Everyman Cinema film releases 
